CREATE TABLE B_LIKE_INFO (
  `LIKE_NO` int NOT NULL,
  `PHOTO_NO` int DEFAULT NULL,
  `REPLY_NO` int DEFAULT NULL,
  `CREATOR` int DEFAULT NULL,
  `CREATE_ON` date DEFAULT NULL,
  PRIMARY KEY (`LIKE_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
